### ISSUE TITLE
Check assignment - Megafon tariffs

### ISSUE THREAD

**Issue by AlekseiILitvinov** [AlekseiILitvinov/Week4HomeworkMegafon#1]

**Comment by coursar** [comment]
Надо было сделать хранение данных, а не отображение (аналог задачи с Tele2)

**Comment by AlekseiILitvinov** [comment]
Оу... Я в задании прочитал, что надо сделать систему классов так, чтобы данные можно было отобразить так, как на пдф. Возможно, я в результате сделал слишком усложненную систему, но наследование и переопределение методов я использовал. Мне кажется, что классы могут хранят все необходимые данные.
